openapi: "3.0.0"
info:
  title: "Model for Factory and Containers"
  description: "Entity definitions to model a factory with sectors and containers"
  version: "1.0.0"
components:
  schemas:
    Factory:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: "Unique identifier of the factory"
        type:
          type: string
          enum: ["Factory"]
          description: "Defines the type as 'Factory'"
        name:
          type: string
          description: "Name of the factory"
        location:
          type: object
          description: "Geographical location of the factory"
          properties:
            type:
              type: string
              enum: ["Point"]
            coordinates:
              type: array
              items:
                type: number
              description: "Latitude and longitude coordinates"
        sectors:
          type: array
          description: "Sectors associated with this factory"
          items:
            $ref: "#/components/schemas/Sector"
      
        ##- sectors  # Torna o array "sectors" obrigatório, mas não o conteúdo específico dos "items"

    Sector:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: "Unique identifier of the sector"
        type:
          type: string
          enum: ["Sector"]
          description: "Defines the type as 'Sector'"
        factoryId:
          type: object
          description: "Relationship with the factory it belongs to"
          properties:
            type:
              type: string
              enum: ["Relationship"]
            object:
              type: string
              description: "ID of the factory"
        location:
          type: object
          description: "Geographical location of the sector"
          properties:
            type:
              type: string
              enum: ["Point"]
            coordinates:
              type: array
              items:
                type: number
              description: "Latitude and longitude coordinates"
        containers:
          type: array
          description: "Containers associated with this sector"
          items:
            $ref: "#/components/schemas/Container"
        porticos:
          type: array
          description: "Porticos associated with this sector"
          items:
            $ref: "#/components/schemas/Portico"
    Portico:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: "Unique identifier of the portico"
        type:
          type: string
          enum: ["Portico"]
          description: "Defines the type as 'Portico'"
        location:
          type: object
          description: "Geographical location of the portico"
          properties:
            type:
              type: string
              enum: ["Point"]
            coordinates:
              type: array
              items:
                type: number
              description: "Latitude and longitude coordinates"
        sensors:
          type: array
          description: "Sensors associated with this portico"
          items:
            $ref: "#/components/schemas/FillingLevelSensor"
    FillingLevelSensor:
      type: object
      required:
        - id
      allOf:
        - $ref: https://fiware.github.io/tutorials.NGSI-LD/models/device.yaml#/Device
      description: >
        A device that consists of a sensor, has the category `saref:Sensor`, and is used to detect the filling level.
      properties:
        id:
          type: string
          description: "Unique identifier of the filling level sensor"
        fillingLevel:
          $ref: https://fiware.github.io/tutorials.NGSI-LD/models/saref-terms.yaml#/fillingLevel
    MotionSensor:
      type: object
      required:
        - id
      allOf:
        - $ref: https://fiware.github.io/tutorials.NGSI-LD/models/device.yaml#/Device
      description: >
        A device that consists of a motion sensor, has the category `saref:Sensor`, and is used to detect motion.
      properties:
        id:
          type: string
          description: "Unique identifier of the motion sensor"
        motion:
          $ref: https://fiware.github.io/tutorials.NGSI-LD/models/saref-terms.yaml#/motion
    Container:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: "Unique identifier of the container"
        type:
          type: string
          enum: ["Container"]
          description: "Defines the type as 'Container'"
        container_code:
          type: object
          description: "Container code"
          properties:
            type:
              type: string
              enum: ["Property"]
            value:
              type: string
              description: "Container identifier code"
        container_volume:
          type: object
          description: "Container volume in liters"
          properties:
            type:
              type: string
              enum: ["Property"]
            value:
              type: number
              description: "Volume in liters"
        sectorId:
          type: object
          description: "Relationship with the sector to which the container belongs"
          properties:
            type:
              type: string
              enum: ["Relationship"]
            object:
              type: string
              description: "ID of the sector"
        active:
          type: object
          description: "Indicates if the container is active"
          properties:
            type:
              type: string
              enum: ["Property"]
            value:
              type: boolean
              description: "Container activity state (true or false)"

paths:
  /ngsi-ld/v1/entities:
    get:
      summary: "Retrieve entities"
      responses:
        "200":
          description: "List of entities"
          content:
            application/ld+json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: "Create a new entity"
      requestBody:
        description: "Entity data to be created"
        content:
          application/ld+json:
            schema:
              $ref: "#/components/schemas/Factory"
      responses:
        "201":
          description: "Entity created successfully"