// <auto-generated />
using System;
using ApiTextPact.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiTextPact.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241205192342_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiTextPact.Models.MotionSensorModel", b =>
                {
                    b.Property<string>("MotionSensorId")
                        .HasColumnType("text");

                    b.Property<bool>("MotionDetected")
                        .HasColumnType("boolean");

                    b.Property<string>("PorticoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MotionSensorId");

                    b.ToTable("MotionSensors");
                });

            modelBuilder.Entity("ApiTextPact.Models.PlantFloorSectionModel", b =>
                {
                    b.Property<string>("PorticId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("PoticName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "https://uri.etsi.org/ngsi-ld/name");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PorticId");

                    b.ToTable("PlantFloorSection");
                });

            modelBuilder.Entity("ContainerLocalizationHistoryModel", b =>
                {
                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContainerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlantFloorSectionModelPorticId")
                        .HasColumnType("text");

                    b.Property<string>("PorticoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ContainerId");

                    b.HasIndex("PlantFloorSectionModelPorticId");

                    b.HasIndex("PorticoId");

                    b.ToTable("ContainerLocalizationHistories");
                });

            modelBuilder.Entity("ContainerModel", b =>
                {
                    b.Property<Guid>("ContainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContainerCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("ContainerDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "http://purl.org/dc/terms/description");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "https://uri.fiware.org/ns/data-models#name");

                    b.Property<float>("ContainerVolume")
                        .HasColumnType("real")
                        .HasAnnotation("Relational:JsonPropertyName", "https://uri.etsi.org/ngsi-ld/default-context/volume");

                    b.HasKey("ContainerId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("ItemInContainerModel", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimeIn")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "https://uri.fiware.org/ns/data-models#capacity");

                    b.Property<DateTime>("DateTimeOut")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "https://uri.fiware.org/ns/data-models");

                    b.HasKey("ItemId");

                    b.HasIndex("ContainerId");

                    b.ToTable("ItemInContainerModel");
                });

            modelBuilder.Entity("ContainerLocalizationHistoryModel", b =>
                {
                    b.HasOne("ContainerModel", "Container")
                        .WithMany("LocalizationHistories")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTextPact.Models.PlantFloorSectionModel", null)
                        .WithMany("LocalizationHistories")
                        .HasForeignKey("PlantFloorSectionModelPorticId");

                    b.HasOne("ApiTextPact.Models.PlantFloorSectionModel", "PlantFloorSection")
                        .WithMany()
                        .HasForeignKey("PorticoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("PlantFloorSection");
                });

            modelBuilder.Entity("ItemInContainerModel", b =>
                {
                    b.HasOne("ContainerModel", "Container")
                        .WithMany("IteminContainers")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("ApiTextPact.Models.PlantFloorSectionModel", b =>
                {
                    b.Navigation("LocalizationHistories");
                });

            modelBuilder.Entity("ContainerModel", b =>
                {
                    b.Navigation("IteminContainers");

                    b.Navigation("LocalizationHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
