// <auto-generated />
using System;
using System.Collections.Generic;
using ApiTexPact.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiTexPact.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250404112008_NewTablesLikeManufacturingPhase")]
    partial class NewTablesLikeManufacturingPhase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiTexPact.Models.CheckpointModel", b =>
                {
                    b.Property<int>("CheckpointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CheckpointId"));

                    b.Property<string>("CheckpointCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("CheckpointId");

                    b.HasIndex("SectionId");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("ApiTexPact.Models.ClientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FiscalNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ApiTexPact.Models.ContainerLocalizationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContainerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "datetime");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("SectionId");

                    b.ToTable("ContainerLocalization");
                });

            modelBuilder.Entity("ApiTexPact.Models.ContainerModel", b =>
                {
                    b.Property<int>("ContainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContainerId"));

                    b.Property<bool>("Activate")
                        .HasColumnType("boolean");

                    b.Property<string>("ContainerCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ContainerVolume")
                        .HasColumnType("real");

                    b.HasKey("ContainerId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("ApiTexPact.Models.EmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ManufacturingPhaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WatchId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingPhaseId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ApiTexPact.Models.ItemInContainerModel", b =>
                {
                    b.Property<int>("ItemInContainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemInContainerId"));

                    b.Property<int>("ContainerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTimeIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTimeOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.HasKey("ItemInContainerId");

                    b.HasIndex("ContainerId");

                    b.ToTable("ItemInContainer");
                });

            modelBuilder.Entity("ApiTexPact.Models.ItemLocalizationModel", b =>
                {
                    b.Property<int>("ItemLocalizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemLocalizationId"));

                    b.Property<int>("ContainerLocalizationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemRawId")
                        .HasColumnType("integer");

                    b.HasKey("ItemLocalizationId");

                    b.HasIndex("ContainerLocalizationId");

                    b.HasIndex("ItemRawId");

                    b.ToTable("ItemLocalization");
                });

            modelBuilder.Entity("ApiTexPact.Models.ItemOfRawMaterialModel", b =>
                {
                    b.Property<int>("ItemRawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemRawId"));

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<int>("ItemInContainerId")
                        .HasColumnType("integer");

                    b.Property<int>("LotOfRawMaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("ManufacturingOrderPhaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemRawId");

                    b.HasIndex("ItemInContainerId");

                    b.HasIndex("LotOfRawMaterialId");

                    b.HasIndex("ManufacturingOrderPhaseId");

                    b.ToTable("ItemOfRawMaterial");
                });

            modelBuilder.Entity("ApiTexPact.Models.LotOfRawMaterialModel", b =>
                {
                    b.Property<int>("LotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LotId"));

                    b.Property<List<int>>("HistoricalWeights")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("LotCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LotQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("LotUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("integer");

                    b.HasKey("LotId");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("LotOfRawMaterial");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingOrderHistoryModel", b =>
                {
                    b.Property<int>("ManufacturingOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("PlantFloorSectionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ManufacturingOrderId", "PlantFloorSectionId");

                    b.HasIndex("PlantFloorSectionId");

                    b.ToTable("ManufacturingOrderHistories");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingOrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("ManufacturingOrderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "ManufacturingPhaseId");

                    b.Property<int>("ManufacturingProcessId")
                        .HasColumnType("integer");

                    b.Property<int>("PhaseDuration")
                        .HasColumnType("integer");

                    b.Property<string>("PhaseInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductLotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ManufacturingProcessId");

                    b.HasIndex("ProductLotId");

                    b.ToTable("ManufacturingOrders");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingOrderPhaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomizationParams")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTimeInit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ManufacturingOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ManufacturingPhaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SheduleInit")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingOrderId");

                    b.HasIndex("ManufacturingPhaseId");

                    b.ToTable("ManufacturingOrderPhases");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingPhaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ManufacturingPhaseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "ManufacturingPhaseId");

                    b.Property<int>("PhaseDuration")
                        .HasColumnType("integer");

                    b.Property<string>("PhaseInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlantFloorSectionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlantFloorSectionId")
                        .IsUnique();

                    b.ToTable("ManufacturingPhases");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingProcessModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ManufacturingProcesses");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingProcessPhaseModel", b =>
                {
                    b.Property<int>("ManufacturingPhaseId")
                        .HasColumnType("integer");

                    b.Property<int>("ManufacturingProcessId")
                        .HasColumnType("integer");

                    b.Property<int>("NumberStepOrder")
                        .HasColumnType("integer");

                    b.HasKey("ManufacturingPhaseId", "ManufacturingProcessId");

                    b.HasIndex("ManufacturingProcessId");

                    b.ToTable("ManufacturingProcessPhases");
                });

            modelBuilder.Entity("ApiTexPact.Models.PlantFloorSectionModel", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SectionId"));

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SectionId");

                    b.ToTable("PlantFloorSection");
                });

            modelBuilder.Entity("ApiTexPact.Models.ProductLotModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LotQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("LotUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductLotId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "ProductLotId");

                    b.Property<bool>("Ready")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductLots");
                });

            modelBuilder.Entity("ApiTexPact.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "ProductId");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ApiTexPact.Models.RawMaterialModel", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RawId"));

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RawId");

                    b.ToTable("RawMaterial");
                });

            modelBuilder.Entity("ApiTexPact.Models.SectionAdminModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("PlantFloorSectionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("PlantFloorSectionId")
                        .IsUnique();

                    b.ToTable("SectionAdminModel");
                });

            modelBuilder.Entity("ApiTexPact.Models.CheckpointModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.PlantFloorSectionModel", "PlantFloorSection")
                        .WithMany("Checkpoints")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantFloorSection");
                });

            modelBuilder.Entity("ApiTexPact.Models.ContainerLocalizationModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ContainerModel", "Container")
                        .WithMany("LocalizationHistories")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.PlantFloorSectionModel", "PlantFloorSection")
                        .WithMany("LocalizationHistories")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("PlantFloorSection");
                });

            modelBuilder.Entity("ApiTexPact.Models.EmployeeModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ManufacturingPhaseModel", "ManufacturingPhase")
                        .WithMany()
                        .HasForeignKey("ManufacturingPhaseId");

                    b.Navigation("ManufacturingPhase");
                });

            modelBuilder.Entity("ApiTexPact.Models.ItemInContainerModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ContainerModel", "Container")
                        .WithMany("IteminContainers")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("ApiTexPact.Models.ItemLocalizationModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ContainerLocalizationModel", "ContainerLocalization")
                        .WithMany("ItemLocalizations")
                        .HasForeignKey("ContainerLocalizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.ItemOfRawMaterialModel", "ItemOfRawMaterial")
                        .WithMany()
                        .HasForeignKey("ItemRawId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContainerLocalization");

                    b.Navigation("ItemOfRawMaterial");
                });

            modelBuilder.Entity("ApiTexPact.Models.ItemOfRawMaterialModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ItemInContainerModel", "ItemInContainer")
                        .WithMany("ItemsOfRawMaterial")
                        .HasForeignKey("ItemInContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.LotOfRawMaterialModel", "LotOfRawMaterial")
                        .WithMany("ItemOfRawMaterials")
                        .HasForeignKey("LotOfRawMaterialId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.ManufacturingOrderPhaseModel", "ManufacturingOrderPhase")
                        .WithMany("ItemOfRawMaterials")
                        .HasForeignKey("ManufacturingOrderPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemInContainer");

                    b.Navigation("LotOfRawMaterial");

                    b.Navigation("ManufacturingOrderPhase");
                });

            modelBuilder.Entity("ApiTexPact.Models.LotOfRawMaterialModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.RawMaterialModel", "RawMaterials")
                        .WithMany("LotOfRawMaterials")
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RawMaterials");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingOrderHistoryModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ManufacturingOrderModel", "ManufacturingOrder")
                        .WithMany("OrderHistory")
                        .HasForeignKey("ManufacturingOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.PlantFloorSectionModel", "PlantFloorSection")
                        .WithMany("OrderHistory")
                        .HasForeignKey("PlantFloorSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManufacturingOrder");

                    b.Navigation("PlantFloorSection");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingOrderModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ClientModel", "Client")
                        .WithMany("ManufacturingOrders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.ManufacturingProcessModel", "ManufacturingProcess")
                        .WithMany("ManufacturingOrders")
                        .HasForeignKey("ManufacturingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.ProductLotModel", "ProductLot")
                        .WithMany()
                        .HasForeignKey("ProductLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ManufacturingProcess");

                    b.Navigation("ProductLot");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingOrderPhaseModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ManufacturingOrderModel", "ManufacturingOrder")
                        .WithMany("ManufacturingOrderPhases")
                        .HasForeignKey("ManufacturingOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.ManufacturingPhaseModel", "ManufacturingPhase")
                        .WithMany("ManufacturingOrderPhases")
                        .HasForeignKey("ManufacturingPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManufacturingOrder");

                    b.Navigation("ManufacturingPhase");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingPhaseModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.PlantFloorSectionModel", "PlantFloorSection")
                        .WithOne("ManufacturingPhase")
                        .HasForeignKey("ApiTexPact.Models.ManufacturingPhaseModel", "PlantFloorSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantFloorSection");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingProcessModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ProductModel", "Product")
                        .WithMany("ManufacturingProcesses")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingProcessPhaseModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ManufacturingPhaseModel", "ManufacturingPhase")
                        .WithMany("ManufacturingProcessPhases")
                        .HasForeignKey("ManufacturingPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.ManufacturingProcessModel", "ManufacturingProcess")
                        .WithMany("ManufacturingProcessPhases")
                        .HasForeignKey("ManufacturingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManufacturingPhase");

                    b.Navigation("ManufacturingProcess");
                });

            modelBuilder.Entity("ApiTexPact.Models.ProductLotModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApiTexPact.Models.SectionAdminModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.EmployeeModel", "Employee")
                        .WithOne()
                        .HasForeignKey("ApiTexPact.Models.SectionAdminModel", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.PlantFloorSectionModel", "PlantFloorSection")
                        .WithOne()
                        .HasForeignKey("ApiTexPact.Models.SectionAdminModel", "PlantFloorSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PlantFloorSection");
                });

            modelBuilder.Entity("ApiTexPact.Models.ClientModel", b =>
                {
                    b.Navigation("ManufacturingOrders");
                });

            modelBuilder.Entity("ApiTexPact.Models.ContainerLocalizationModel", b =>
                {
                    b.Navigation("ItemLocalizations");
                });

            modelBuilder.Entity("ApiTexPact.Models.ContainerModel", b =>
                {
                    b.Navigation("IteminContainers");

                    b.Navigation("LocalizationHistories");
                });

            modelBuilder.Entity("ApiTexPact.Models.ItemInContainerModel", b =>
                {
                    b.Navigation("ItemsOfRawMaterial");
                });

            modelBuilder.Entity("ApiTexPact.Models.LotOfRawMaterialModel", b =>
                {
                    b.Navigation("ItemOfRawMaterials");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingOrderModel", b =>
                {
                    b.Navigation("ManufacturingOrderPhases");

                    b.Navigation("OrderHistory");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingOrderPhaseModel", b =>
                {
                    b.Navigation("ItemOfRawMaterials");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingPhaseModel", b =>
                {
                    b.Navigation("ManufacturingOrderPhases");

                    b.Navigation("ManufacturingProcessPhases");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingProcessModel", b =>
                {
                    b.Navigation("ManufacturingOrders");

                    b.Navigation("ManufacturingProcessPhases");
                });

            modelBuilder.Entity("ApiTexPact.Models.PlantFloorSectionModel", b =>
                {
                    b.Navigation("Checkpoints");

                    b.Navigation("LocalizationHistories");

                    b.Navigation("ManufacturingPhase")
                        .IsRequired();

                    b.Navigation("OrderHistory");
                });

            modelBuilder.Entity("ApiTexPact.Models.ProductModel", b =>
                {
                    b.Navigation("ManufacturingProcesses");
                });

            modelBuilder.Entity("ApiTexPact.Models.RawMaterialModel", b =>
                {
                    b.Navigation("LotOfRawMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
