// <auto-generated />
using System;
using Drivolution.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drivolution.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260628111025_AddAuditLog")]
    partial class AddAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drivolution.Models.AlertModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<int?>("EstimatedDuration")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("OrderFrom")
                        .HasColumnType("integer")
                        .HasColumnName("order_from");

                    b.Property<int?>("OrderTo")
                        .HasColumnType("integer")
                        .HasColumnName("order_to");

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase_name");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("ProductPhaseId")
                        .HasColumnType("integer")
                        .HasColumnName("product_phase_id");

                    b.Property<string>("ProductSerial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_serial");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("ThresholdPct")
                        .HasColumnType("integer")
                        .HasColumnName("threshold_pct");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("triggered_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductPhaseId");

                    b.ToTable("alert");
                });

            modelBuilder.Entity("Drivolution.Models.AuditLogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_label");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("Drivolution.Models.CarModelModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("model");
                });

            modelBuilder.Entity("Drivolution.Models.ClientOrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.ToTable("client_order");
                });

            modelBuilder.Entity("Drivolution.Models.ConfigModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowMultiple")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_multiple");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("config");
                });

            modelBuilder.Entity("Drivolution.Models.ConfigOptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("config_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.ToTable("config_option");
                });

            modelBuilder.Entity("Drivolution.Models.LocalizationHistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatetimeEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datetime_end");

                    b.Property<DateTime>("DatetimeIni")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datetime_ini");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("SupportId")
                        .HasColumnType("integer")
                        .HasColumnName("support_id");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("SupportId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("localization_history");
                });

            modelBuilder.Entity("Drivolution.Models.ManufacturingOrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("client_order_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("ManufacturingOrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manufacturing_order_number");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId");

                    b.ToTable("manufacturing_order");
                });

            modelBuilder.Entity("Drivolution.Models.ManufacturingPhaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EstimatedDuration")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration");

                    b.Property<string>("MaxAcceptableSeverity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("max_acceptable_severity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ReworkSeverity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rework_severity");

                    b.Property<int>("TimeThresholdPct")
                        .HasColumnType("integer")
                        .HasColumnName("time_threshold_pct");

                    b.HasKey("Id");

                    b.ToTable("manufacturing_phase");
                });

            modelBuilder.Entity("Drivolution.Models.MaterialModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item");

                    b.Property<string>("PartNumber")
                        .HasColumnType("text")
                        .HasColumnName("part_number");

                    b.HasKey("Id");

                    b.ToTable("material");
                });

            modelBuilder.Entity("Drivolution.Models.ModelMaterialModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturingPhaseId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_phase_id");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("material_id");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingPhaseId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ModelId");

                    b.ToTable("model_material");
                });

            modelBuilder.Entity("Drivolution.Models.PhaseSequenceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturingPhaseId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_phase_id");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingPhaseId");

                    b.HasIndex("ModelId");

                    b.ToTable("phase_sequence");
                });

            modelBuilder.Entity("Drivolution.Models.PhaseTimeCoefficientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfigOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("config_option_id");

                    b.Property<int>("ManufacturingPhaseId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_phase_id");

                    b.Property<int?>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<int?>("ProductionLineId")
                        .HasColumnType("integer")
                        .HasColumnName("production_line_id");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("trained_at");

                    b.Property<decimal>("WeightSeconds")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_seconds");

                    b.HasKey("Id");

                    b.HasIndex("ConfigOptionId");

                    b.HasIndex("ManufacturingPhaseId");

                    b.HasIndex("ModelId");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("phase_time_coefficient");
                });

            modelBuilder.Entity("Drivolution.Models.ProductConfigModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("config_option_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ConfigOptionId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_config");
                });

            modelBuilder.Entity("Drivolution.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LotNumber")
                        .HasColumnType("text")
                        .HasColumnName("lot_number");

                    b.Property<int>("ManufacturingOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_order_id");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("production_date");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingOrderId");

                    b.HasIndex("ModelId");

                    b.ToTable("product");
                });

            modelBuilder.Entity("Drivolution.Models.ProductPhaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatetimeEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datetime_end");

                    b.Property<DateTime>("DatetimeIni")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datetime_ini");

                    b.Property<int>("ManufacturingPhaseId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_phase_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("QualityId")
                        .HasColumnType("integer")
                        .HasColumnName("quality_id");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingPhaseId");

                    b.HasIndex("ProductId");

                    b.HasIndex("QualityId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("product_phase");
                });

            modelBuilder.Entity("Drivolution.Models.ProductionLineModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("production_line");
                });

            modelBuilder.Entity("Drivolution.Models.QualityCheckModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturingPhaseId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_phase_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingPhaseId");

                    b.HasIndex("ProductId");

                    b.ToTable("quality_check");
                });

            modelBuilder.Entity("Drivolution.Models.ResourceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsHuman")
                        .HasColumnType("boolean")
                        .HasColumnName("is_human");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("resource");
                });

            modelBuilder.Entity("Drivolution.Models.SupportModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductionLineId")
                        .HasColumnType("integer")
                        .HasColumnName("production_line_id");

                    b.Property<string>("RfidTag")
                        .HasColumnType("text")
                        .HasColumnName("rfid_tag");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("support");
                });

            modelBuilder.Entity("Drivolution.Models.SupportedProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatetimeEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datetime_end");

                    b.Property<DateTime>("DatetimeIni")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datetime_ini");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("SupportId")
                        .HasColumnType("integer")
                        .HasColumnName("support_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupportId");

                    b.ToTable("supported_product");
                });

            modelBuilder.Entity("Drivolution.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("app_user");
                });

            modelBuilder.Entity("Drivolution.Models.WorkstationAllocationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("workstation_allocation");
                });

            modelBuilder.Entity("Drivolution.Models.WorkstationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int?>("ManufacturingPhaseId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_phase_id");

                    b.Property<int>("ProductionLineId")
                        .HasColumnType("integer")
                        .HasColumnName("production_line_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingPhaseId");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("workstation");
                });

            modelBuilder.Entity("Drivolution.Models.WorkstationPresenceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer")
                        .HasColumnName("app_user_id");

                    b.Property<DateTime>("CheckedInAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("checked_in_at");

                    b.Property<DateTime?>("CheckedOutAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("checked_out_at");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("workstation_presence");
                });

            modelBuilder.Entity("Drivolution.Models.WorkstationStatusModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkstationId");

                    b.ToTable("workstation_status");
                });

            modelBuilder.Entity("Drivolution.Models.AlertModel", b =>
                {
                    b.HasOne("Drivolution.Models.ProductModel", "Product")
                        .WithMany("Alerts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drivolution.Models.ProductPhaseModel", "ProductPhase")
                        .WithMany("Alerts")
                        .HasForeignKey("ProductPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductPhase");
                });

            modelBuilder.Entity("Drivolution.Models.ConfigModel", b =>
                {
                    b.HasOne("Drivolution.Models.CarModelModel", "CarModel")
                        .WithMany("Configs")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("Drivolution.Models.ConfigOptionModel", b =>
                {
                    b.HasOne("Drivolution.Models.ConfigModel", "Config")
                        .WithMany("ConfigOptions")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("Drivolution.Models.LocalizationHistoryModel", b =>
                {
                    b.HasOne("Drivolution.Models.SupportModel", "Support")
                        .WithMany("LocalizationHistories")
                        .HasForeignKey("SupportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Drivolution.Models.WorkstationModel", "Workstation")
                        .WithMany("LocalizationHistories")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Support");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Drivolution.Models.ManufacturingOrderModel", b =>
                {
                    b.HasOne("Drivolution.Models.ClientOrderModel", "ClientOrder")
                        .WithMany("ManufacturingOrders")
                        .HasForeignKey("ClientOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientOrder");
                });

            modelBuilder.Entity("Drivolution.Models.ModelMaterialModel", b =>
                {
                    b.HasOne("Drivolution.Models.ManufacturingPhaseModel", "ManufacturingPhase")
                        .WithMany("ModelMaterials")
                        .HasForeignKey("ManufacturingPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Drivolution.Models.MaterialModel", "Material")
                        .WithMany("ModelMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Drivolution.Models.CarModelModel", "CarModel")
                        .WithMany("ModelMaterials")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("ManufacturingPhase");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Drivolution.Models.PhaseSequenceModel", b =>
                {
                    b.HasOne("Drivolution.Models.ManufacturingPhaseModel", "ManufacturingPhase")
                        .WithMany("PhaseSequences")
                        .HasForeignKey("ManufacturingPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Drivolution.Models.CarModelModel", "CarModel")
                        .WithMany("PhaseSequences")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("ManufacturingPhase");
                });

            modelBuilder.Entity("Drivolution.Models.PhaseTimeCoefficientModel", b =>
                {
                    b.HasOne("Drivolution.Models.ConfigOptionModel", "ConfigOption")
                        .WithMany()
                        .HasForeignKey("ConfigOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Drivolution.Models.ManufacturingPhaseModel", "ManufacturingPhase")
                        .WithMany()
                        .HasForeignKey("ManufacturingPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Drivolution.Models.CarModelModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Drivolution.Models.ProductionLineModel", "ProductionLine")
                        .WithMany()
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CarModel");

                    b.Navigation("ConfigOption");

                    b.Navigation("ManufacturingPhase");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("Drivolution.Models.ProductConfigModel", b =>
                {
                    b.HasOne("Drivolution.Models.ConfigOptionModel", "ConfigOption")
                        .WithMany()
                        .HasForeignKey("ConfigOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Drivolution.Models.ProductModel", "Product")
                        .WithMany("ProductConfigs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigOption");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Drivolution.Models.ProductModel", b =>
                {
                    b.HasOne("Drivolution.Models.ManufacturingOrderModel", "ManufacturingOrder")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturingOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Drivolution.Models.CarModelModel", "CarModel")
                        .WithMany("Products")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("ManufacturingOrder");
                });

            modelBuilder.Entity("Drivolution.Models.ProductPhaseModel", b =>
                {
                    b.HasOne("Drivolution.Models.ManufacturingPhaseModel", "ManufacturingPhase")
                        .WithMany("ProductPhases")
                        .HasForeignKey("ManufacturingPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Drivolution.Models.ProductModel", "Product")
                        .WithMany("ProductPhases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drivolution.Models.QualityCheckModel", "QualityCheck")
                        .WithMany("ProductPhases")
                        .HasForeignKey("QualityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Drivolution.Models.WorkstationModel", "Workstation")
                        .WithMany("ProductPhases")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManufacturingPhase");

                    b.Navigation("Product");

                    b.Navigation("QualityCheck");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Drivolution.Models.QualityCheckModel", b =>
                {
                    b.HasOne("Drivolution.Models.ManufacturingPhaseModel", "ManufacturingPhase")
                        .WithMany("QualityChecks")
                        .HasForeignKey("ManufacturingPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Drivolution.Models.ProductModel", "Product")
                        .WithMany("QualityChecks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManufacturingPhase");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Drivolution.Models.SupportModel", b =>
                {
                    b.HasOne("Drivolution.Models.ProductionLineModel", "ProductionLine")
                        .WithMany("Supports")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("Drivolution.Models.SupportedProductModel", b =>
                {
                    b.HasOne("Drivolution.Models.ProductModel", "Product")
                        .WithMany("SupportedProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Drivolution.Models.SupportModel", "Support")
                        .WithMany("SupportedProducts")
                        .HasForeignKey("SupportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Support");
                });

            modelBuilder.Entity("Drivolution.Models.WorkstationAllocationModel", b =>
                {
                    b.HasOne("Drivolution.Models.ResourceModel", "Resource")
                        .WithMany("WorkstationAllocations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Drivolution.Models.WorkstationModel", "Workstation")
                        .WithMany("WorkstationAllocations")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Drivolution.Models.WorkstationModel", b =>
                {
                    b.HasOne("Drivolution.Models.ManufacturingPhaseModel", "ManufacturingPhase")
                        .WithMany()
                        .HasForeignKey("ManufacturingPhaseId");

                    b.HasOne("Drivolution.Models.ProductionLineModel", "ProductionLine")
                        .WithMany("Workstations")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManufacturingPhase");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("Drivolution.Models.WorkstationPresenceModel", b =>
                {
                    b.HasOne("Drivolution.Models.UserModel", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Drivolution.Models.WorkstationModel", "Workstation")
                        .WithMany("WorkstationPresences")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Drivolution.Models.WorkstationStatusModel", b =>
                {
                    b.HasOne("Drivolution.Models.WorkstationModel", "Workstation")
                        .WithMany("WorkstationStatuses")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Drivolution.Models.CarModelModel", b =>
                {
                    b.Navigation("Configs");

                    b.Navigation("ModelMaterials");

                    b.Navigation("PhaseSequences");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Drivolution.Models.ClientOrderModel", b =>
                {
                    b.Navigation("ManufacturingOrders");
                });

            modelBuilder.Entity("Drivolution.Models.ConfigModel", b =>
                {
                    b.Navigation("ConfigOptions");
                });

            modelBuilder.Entity("Drivolution.Models.ManufacturingOrderModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Drivolution.Models.ManufacturingPhaseModel", b =>
                {
                    b.Navigation("ModelMaterials");

                    b.Navigation("PhaseSequences");

                    b.Navigation("ProductPhases");

                    b.Navigation("QualityChecks");
                });

            modelBuilder.Entity("Drivolution.Models.MaterialModel", b =>
                {
                    b.Navigation("ModelMaterials");
                });

            modelBuilder.Entity("Drivolution.Models.ProductModel", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("ProductConfigs");

                    b.Navigation("ProductPhases");

                    b.Navigation("QualityChecks");

                    b.Navigation("SupportedProducts");
                });

            modelBuilder.Entity("Drivolution.Models.ProductPhaseModel", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("Drivolution.Models.ProductionLineModel", b =>
                {
                    b.Navigation("Supports");

                    b.Navigation("Workstations");
                });

            modelBuilder.Entity("Drivolution.Models.QualityCheckModel", b =>
                {
                    b.Navigation("ProductPhases");
                });

            modelBuilder.Entity("Drivolution.Models.ResourceModel", b =>
                {
                    b.Navigation("WorkstationAllocations");
                });

            modelBuilder.Entity("Drivolution.Models.SupportModel", b =>
                {
                    b.Navigation("LocalizationHistories");

                    b.Navigation("SupportedProducts");
                });

            modelBuilder.Entity("Drivolution.Models.WorkstationModel", b =>
                {
                    b.Navigation("LocalizationHistories");

                    b.Navigation("ProductPhases");

                    b.Navigation("WorkstationAllocations");

                    b.Navigation("WorkstationPresences");

                    b.Navigation("WorkstationStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
