// <auto-generated />
using System;
using ApiTexPact.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiTexPact.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiTexPact.Models.CarModelModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("model");
                });

            modelBuilder.Entity("ApiTexPact.Models.ClientOrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.HasKey("Id");

                    b.ToTable("client_order");
                });

            modelBuilder.Entity("ApiTexPact.Models.ConfigModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text")
                        .HasColumnName("default_value");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("config");
                });

            modelBuilder.Entity("ApiTexPact.Models.LocalizationHistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatetimeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime_end");

                    b.Property<DateTime>("DatetimeIni")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime_ini");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("SupportId")
                        .HasColumnType("integer")
                        .HasColumnName("support_id");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("SupportId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("localization_history");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingOrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("client_order_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("ManufacturingOrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manufacturing_order_number");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId");

                    b.ToTable("manufacturing_order");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingPhaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EstimatedDuration")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("manufacturing_phase");
                });

            modelBuilder.Entity("ApiTexPact.Models.MaterialModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item");

                    b.Property<string>("PartNumber")
                        .HasColumnType("text")
                        .HasColumnName("part_number");

                    b.HasKey("Id");

                    b.ToTable("material");
                });

            modelBuilder.Entity("ApiTexPact.Models.ModelMaterialModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturingPhaseId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_phase_id");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("material_id");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingPhaseId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ModelId");

                    b.ToTable("model_material");
                });

            modelBuilder.Entity("ApiTexPact.Models.PhaseSequenceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturingPhaseId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_phase_id");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingPhaseId");

                    b.HasIndex("ModelId");

                    b.ToTable("phase_sequence");
                });

            modelBuilder.Entity("ApiTexPact.Models.ProductConfigModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("config_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_config");
                });

            modelBuilder.Entity("ApiTexPact.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasColumnType("text")
                        .HasColumnName("color_code");

                    b.Property<string>("LotNumber")
                        .HasColumnType("text")
                        .HasColumnName("lot_number");

                    b.Property<int>("ManufacturingOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_order_id");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("production_date");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingOrderId");

                    b.HasIndex("ModelId");

                    b.ToTable("product");
                });

            modelBuilder.Entity("ApiTexPact.Models.ProductPhaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<DateTime?>("DatetimeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime_end");

                    b.Property<DateTime>("DatetimeIni")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime_ini");

                    b.Property<int>("ManufacturingPhaseId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_phase_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("QualityId")
                        .HasColumnType("integer")
                        .HasColumnName("quality_id");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingPhaseId");

                    b.HasIndex("ProductId");

                    b.HasIndex("QualityId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("product_phase");
                });

            modelBuilder.Entity("ApiTexPact.Models.ProductionLineModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("production_line");
                });

            modelBuilder.Entity("ApiTexPact.Models.QualityCheckModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturingPhaseId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_phase_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingPhaseId");

                    b.HasIndex("ProductId");

                    b.ToTable("quality_check");
                });

            modelBuilder.Entity("ApiTexPact.Models.ResourceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsHuman")
                        .HasColumnType("boolean")
                        .HasColumnName("is_human");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("resource");
                });

            modelBuilder.Entity("ApiTexPact.Models.SupportModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductionLineId")
                        .HasColumnType("integer")
                        .HasColumnName("production_line_id");

                    b.Property<string>("RfidTag")
                        .HasColumnType("text")
                        .HasColumnName("rfid_tag");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("support");
                });

            modelBuilder.Entity("ApiTexPact.Models.SupportedProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatetimeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime_end");

                    b.Property<DateTime>("DatetimeIni")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime_ini");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("SupportId")
                        .HasColumnType("integer")
                        .HasColumnName("support_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupportId");

                    b.ToTable("supported_product");
                });

            modelBuilder.Entity("ApiTexPact.Models.WorkstationAllocationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("workstation_allocation");
                });

            modelBuilder.Entity("ApiTexPact.Models.WorkstationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductionLineId")
                        .HasColumnType("integer")
                        .HasColumnName("production_line_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("workstation");
                });

            modelBuilder.Entity("ApiTexPact.Models.WorkstationStatusModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkstationId");

                    b.ToTable("workstation_status");
                });

            modelBuilder.Entity("ApiTexPact.Models.ConfigModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.CarModelModel", "CarModel")
                        .WithMany("Configs")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("ApiTexPact.Models.LocalizationHistoryModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.SupportModel", "Support")
                        .WithMany("LocalizationHistories")
                        .HasForeignKey("SupportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.WorkstationModel", "Workstation")
                        .WithMany("LocalizationHistories")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Support");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingOrderModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ClientOrderModel", "ClientOrder")
                        .WithMany("ManufacturingOrders")
                        .HasForeignKey("ClientOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientOrder");
                });

            modelBuilder.Entity("ApiTexPact.Models.ModelMaterialModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ManufacturingPhaseModel", "ManufacturingPhase")
                        .WithMany("ModelMaterials")
                        .HasForeignKey("ManufacturingPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.MaterialModel", "Material")
                        .WithMany("ModelMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.CarModelModel", "CarModel")
                        .WithMany("ModelMaterials")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("ManufacturingPhase");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ApiTexPact.Models.PhaseSequenceModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ManufacturingPhaseModel", "ManufacturingPhase")
                        .WithMany("PhaseSequences")
                        .HasForeignKey("ManufacturingPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.CarModelModel", "CarModel")
                        .WithMany("PhaseSequences")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("ManufacturingPhase");
                });

            modelBuilder.Entity("ApiTexPact.Models.ProductConfigModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ConfigModel", "Config")
                        .WithMany("ProductConfigs")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.ProductModel", "Product")
                        .WithMany("ProductConfigs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApiTexPact.Models.ProductModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ManufacturingOrderModel", "ManufacturingOrder")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturingOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.CarModelModel", "CarModel")
                        .WithMany("Products")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("ManufacturingOrder");
                });

            modelBuilder.Entity("ApiTexPact.Models.ProductPhaseModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ManufacturingPhaseModel", "ManufacturingPhase")
                        .WithMany("ProductPhases")
                        .HasForeignKey("ManufacturingPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.ProductModel", "Product")
                        .WithMany("ProductPhases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.QualityCheckModel", "QualityCheck")
                        .WithMany("ProductPhases")
                        .HasForeignKey("QualityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiTexPact.Models.WorkstationModel", "Workstation")
                        .WithMany("ProductPhases")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManufacturingPhase");

                    b.Navigation("Product");

                    b.Navigation("QualityCheck");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("ApiTexPact.Models.QualityCheckModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ManufacturingPhaseModel", "ManufacturingPhase")
                        .WithMany("QualityChecks")
                        .HasForeignKey("ManufacturingPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.ProductModel", "Product")
                        .WithMany("QualityChecks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManufacturingPhase");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApiTexPact.Models.SupportModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ProductionLineModel", "ProductionLine")
                        .WithMany("Supports")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("ApiTexPact.Models.SupportedProductModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ProductModel", "Product")
                        .WithMany("SupportedProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiTexPact.Models.SupportModel", "Support")
                        .WithMany("SupportedProducts")
                        .HasForeignKey("SupportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Support");
                });

            modelBuilder.Entity("ApiTexPact.Models.WorkstationAllocationModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ResourceModel", "Resource")
                        .WithMany("WorkstationAllocations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTexPact.Models.WorkstationModel", "Workstation")
                        .WithMany("WorkstationAllocations")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("ApiTexPact.Models.WorkstationModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.ProductionLineModel", "ProductionLine")
                        .WithMany("Workstations")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("ApiTexPact.Models.WorkstationStatusModel", b =>
                {
                    b.HasOne("ApiTexPact.Models.WorkstationModel", "Workstation")
                        .WithMany("WorkstationStatuses")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("ApiTexPact.Models.CarModelModel", b =>
                {
                    b.Navigation("Configs");

                    b.Navigation("ModelMaterials");

                    b.Navigation("PhaseSequences");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ApiTexPact.Models.ClientOrderModel", b =>
                {
                    b.Navigation("ManufacturingOrders");
                });

            modelBuilder.Entity("ApiTexPact.Models.ConfigModel", b =>
                {
                    b.Navigation("ProductConfigs");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingOrderModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ApiTexPact.Models.ManufacturingPhaseModel", b =>
                {
                    b.Navigation("ModelMaterials");

                    b.Navigation("PhaseSequences");

                    b.Navigation("ProductPhases");

                    b.Navigation("QualityChecks");
                });

            modelBuilder.Entity("ApiTexPact.Models.MaterialModel", b =>
                {
                    b.Navigation("ModelMaterials");
                });

            modelBuilder.Entity("ApiTexPact.Models.ProductModel", b =>
                {
                    b.Navigation("ProductConfigs");

                    b.Navigation("ProductPhases");

                    b.Navigation("QualityChecks");

                    b.Navigation("SupportedProducts");
                });

            modelBuilder.Entity("ApiTexPact.Models.ProductionLineModel", b =>
                {
                    b.Navigation("Supports");

                    b.Navigation("Workstations");
                });

            modelBuilder.Entity("ApiTexPact.Models.QualityCheckModel", b =>
                {
                    b.Navigation("ProductPhases");
                });

            modelBuilder.Entity("ApiTexPact.Models.ResourceModel", b =>
                {
                    b.Navigation("WorkstationAllocations");
                });

            modelBuilder.Entity("ApiTexPact.Models.SupportModel", b =>
                {
                    b.Navigation("LocalizationHistories");

                    b.Navigation("SupportedProducts");
                });

            modelBuilder.Entity("ApiTexPact.Models.WorkstationModel", b =>
                {
                    b.Navigation("LocalizationHistories");

                    b.Navigation("ProductPhases");

                    b.Navigation("WorkstationAllocations");

                    b.Navigation("WorkstationStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
