version: '3.8'

services:
  # Orion is an NGSI-v2 context broker
  orion:
    platform: linux/x86_64
    image: fiware/orion-ld
    hostname: orion
    container_name: fiware--orion
    depends_on:
      - mongo-db
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG
    healthcheck:
      test: [ "CMD", "curl", "--fail", "-s", "http://orion:1026/version" ]
      interval: 5s

  # IoT-Agent is configured for the Custom XML Protocol
  iot-agent:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/iotagent-ul:${ULTRALIGHT_VERSION}
    hostname: iot-agent
    container_name: fiware--iot--agent
    depends_on:
      - mongo-db
    networks:
      - default
    expose:
      - "${IOTA_NORTH_PORT}"
      - "${IOTA_SOUTH_PORT}"
    ports:
      - "${IOTA_NORTH_PORT}:${IOTA_NORTH_PORT}" # localhost:4041
      - "${IOTA_SOUTH_PORT}:${IOTA_SOUTH_PORT}" # localhost:7896
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=${IOTA_NORTH_PORT}
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_TIMESTAMP=true
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_AUTOCAST=true
      - IOTA_MONGO_HOST=mongo-db
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagentul
      - IOTA_HTTP_PORT=${IOTA_SOUTH_PORT}
      - IOTA_PROVIDER_URL=http://iot-agent:${IOTA_NORTH_PORT}
      - IOTA_DEFAULT_RESOURCE=/iot/d
    healthcheck:
      interval: 5s

  # MongoDB for storing IoT Agent data
  mongo-db:
    labels:
      org.fiware: 'tutorial'
    image: mongo:${MONGO_DB_VERSION}
    hostname: mongo-db
    container_name: mongo-db
    expose:
      - "${MONGO_DB_PORT}"
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}" # localhost:27017
    networks:
      - default
    volumes:
      - mongo-db:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Keycloak for authentication
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    hostname: keycloak
    container_name: keycloak
    command: start
    depends_on:
      - db
    ports:
      - "10000:10000"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=texpact
      - KC_BOOTSTRAP_ADMIN_PASSWORD=texpact
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak?ssl=allow
      - KC_DB_USERNAME=texpact
      - KC_DB_PASSWORD=texpact
      - KC_HTTP_PORT=10000

  # Quantum Leap for context data
  quantumleap:
    image: fiware/quantum-leap
    ports:
      - "8668:8668"
    depends_on:
      - mongo-db
      - orion
      - crate
    environment:
      - CRATE_HOST=${CRATE_HOST:-crate}
      - USE_GEOCODING=True
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOGLEVEL=DEBUG

  # CrateDB for data storage
  crate:
    image: crate:${CRATE_VERSION:-4.6.7}
    command: crate -Cauth.host_based.enabled=false -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    environment:
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    ports:
      - "4200:4200" # Admin UI
      - "4300:4300" # Transport protocol
    volumes:
      - cratedata:/data


  # Grafana for data visualization
  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - '3003:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

  # PostgreSQL database
  db:
    image: postgres:15
    hostname: db
    container_name: texpact-db
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_USER: texpact
      POSTGRES_PASSWORD: texpact
      POSTGRES_DB: texpact

networks:
  default:
    labels:
      org.fiware: 'tutorial'
    ipam:
      config:
        - subnet: 172.18.1.0/24

volumes:
  mongo-db:
  cratedata: