# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-12-04T17:57:34+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Position(Enum):
    before = 'before'
    middle = 'middle'
    after = 'after'


class State(Enum):
    active = 'active'
    inactive = 'inactive'


class Sensor(BaseModel):
    id: str = Field(..., description='Unique identifier for the sensor.')
    name: str = Field(..., description='Name of the sensor.')
    description: str = Field(..., description='Detailed description of the sensor.')
    type: str = Field(
        ..., description='Type of the sensor (e.g., "position", "weight", etc.).'
    )
    state: State = Field(..., description='State of the sensor (active or inactive).')


class Container(BaseModel):
    id: str = Field(..., description='Unique identifier for the container.')
    name: str = Field(..., description='Name of the container.')
    description: str = Field(..., description='Detailed description of the container.')
    capacity: int = Field(
        ...,
        description='Capacity of the container (in cubic meters or appropriate unit).',
    )


class SensorGroup1(BaseModel):
    id: str = Field(..., description='Unique identifier for the sensor group.')
    name: str = Field(..., description='Name of the sensor group.')
    description: Optional[str] = Field(
        None, description='Detailed description of the sensor group.'
    )
    position: Position = Field(
        ...,
        description='Position of the sensor group in the checkpoint (e.g., before, middle, or after).',
    )
    sensors: List[Sensor] = Field(..., description='Array of sensors within the group.')


class Sensor1(BaseModel):
    id: str = Field(..., description='Unique identifier for the sensor.')
    name: str = Field(..., description='Name of the sensor.')
    description: str = Field(..., description='Detailed description of the sensor.')
    type: str = Field(
        ..., description='Type of the sensor (e.g., "position", "weight", etc.).'
    )
    state: State = Field(..., description='State of the sensor (active or inactive).')


class SensorGroup(BaseModel):
    id: str = Field(..., description='Unique identifier for the sensor group.')
    name: str = Field(..., description='Name of the sensor group.')
    description: Optional[str] = Field(
        None, description='Detailed description of the sensor group.'
    )
    position: Position = Field(
        ...,
        description='Position of the sensor group in the checkpoint (e.g., before, middle, or after).',
    )
    sensors: List[Sensor] = Field(..., description='Array of sensors within the group.')


class Checkpoint(BaseModel):
    id: str = Field(..., description='Unique identifier for the checkpoint.')
    name: str = Field(..., description='Name of the checkpoint.')
    description: str = Field(
        ...,
        description='Detailed description of the checkpoint, including its use and specifications.',
    )
    sensorGroups: List[SensorGroup] = Field(
        ...,
        description='List of sensor groups associated with the checkpoint, including the position of each group.',
    )


class Sector(BaseModel):
    id: str = Field(..., description='Unique identifier for the sector.')
    name: str = Field(..., description='Name of the sector.')
    description: str = Field(..., description='Detailed description of the sector.')
    checkpoints: List[Checkpoint] = Field(
        ..., description='List of checkpoints within the sector.'
    )
    containers: List[Container] = Field(
        ..., description='List of containers within the sector.'
    )


class Factory(BaseModel):
    id: str = Field(..., description='Unique identifier for the factory.')
    name: str = Field(..., description='Name of the factory.')
    description: str = Field(..., description='Detailed description of the factory.')
    location: str = Field(..., description='Physical location of the factory.')
    typeIndustry: str = Field(
        ..., description='The type of industry the factory operates in.'
    )
    numberOfEmployees: int = Field(
        ..., description='The number of employees working at the factory.'
    )
    sectors: List[Sector] = Field(
        ..., description='List of sectors within the factory.'
    )
