# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: checkpoint.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'checkpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63heckpoint.proto\x12\x07texpact\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n\x0f\x43heckpointField\x12\x0c\n\x04name\x18\x01 \x01(\t\"y\n\nCheckpoint\x12\x14\n\x0c\x63heckpointId\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\x12&\n\x04name\x18\x03 \x01(\x0b\x32\x18.texpact.CheckpointField\x12\x0e\n\x06status\x18\x04 \x01(\x08\x12\x11\n\tsectionId\x18\x05 \x01(\x05\":\n\x0e\x43heckpointList\x12(\n\x0b\x63heckpoints\x18\x01 \x03(\x0b\x32\x13.texpact.Checkpoint\"%\n\x10SectionIdRequest\x12\x11\n\tsectionId\x18\x01 \x01(\x05\"+\n\x13\x43heckpointIdRequest\x12\x14\n\x0c\x63heckpointId\x18\x01 \x01(\x05\x32\xef\x01\n\x11\x43heckpointService\x12\x42\n\x0fListCheckpoints\x12\x16.google.protobuf.Empty\x1a\x17.texpact.CheckpointList\x12\x46\n\x11GetCheckpointById\x12\x1c.texpact.CheckpointIdRequest\x1a\x13.texpact.Checkpoint\x12N\n\x18ListCheckpointsBySection\x12\x19.texpact.SectionIdRequest\x1a\x17.texpact.CheckpointListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checkpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKPOINTFIELD']._serialized_start=58
  _globals['_CHECKPOINTFIELD']._serialized_end=89
  _globals['_CHECKPOINT']._serialized_start=91
  _globals['_CHECKPOINT']._serialized_end=212
  _globals['_CHECKPOINTLIST']._serialized_start=214
  _globals['_CHECKPOINTLIST']._serialized_end=272
  _globals['_SECTIONIDREQUEST']._serialized_start=274
  _globals['_SECTIONIDREQUEST']._serialized_end=311
  _globals['_CHECKPOINTIDREQUEST']._serialized_start=313
  _globals['_CHECKPOINTIDREQUEST']._serialized_end=356
  _globals['_CHECKPOINTSERVICE']._serialized_start=359
  _globals['_CHECKPOINTSERVICE']._serialized_end=598
# @@protoc_insertion_point(module_scope)
