# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import checkpoint_pb2 as checkpoint__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in checkpoint_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CheckpointServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCheckpoints = channel.unary_unary(
                '/texpact.CheckpointService/ListCheckpoints',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=checkpoint__pb2.CheckpointList.FromString,
                _registered_method=True)
        self.GetCheckpointById = channel.unary_unary(
                '/texpact.CheckpointService/GetCheckpointById',
                request_serializer=checkpoint__pb2.CheckpointIdRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.Checkpoint.FromString,
                _registered_method=True)
        self.ListCheckpointsBySection = channel.unary_unary(
                '/texpact.CheckpointService/ListCheckpointsBySection',
                request_serializer=checkpoint__pb2.SectionIdRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.CheckpointList.FromString,
                _registered_method=True)


class CheckpointServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListCheckpoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckpointById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCheckpointsBySection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckpointServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCheckpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCheckpoints,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=checkpoint__pb2.CheckpointList.SerializeToString,
            ),
            'GetCheckpointById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpointById,
                    request_deserializer=checkpoint__pb2.CheckpointIdRequest.FromString,
                    response_serializer=checkpoint__pb2.Checkpoint.SerializeToString,
            ),
            'ListCheckpointsBySection': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCheckpointsBySection,
                    request_deserializer=checkpoint__pb2.SectionIdRequest.FromString,
                    response_serializer=checkpoint__pb2.CheckpointList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'texpact.CheckpointService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('texpact.CheckpointService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CheckpointService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCheckpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.CheckpointService/ListCheckpoints',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            checkpoint__pb2.CheckpointList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckpointById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.CheckpointService/GetCheckpointById',
            checkpoint__pb2.CheckpointIdRequest.SerializeToString,
            checkpoint__pb2.Checkpoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCheckpointsBySection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.CheckpointService/ListCheckpointsBySection',
            checkpoint__pb2.SectionIdRequest.SerializeToString,
            checkpoint__pb2.CheckpointList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
