# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clients.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'clients.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rclients.proto\x12\x07texpact\"\x07\n\x05\x45mpty\"$\n\x0f\x43lientIdRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"8\n\x06\x43lient\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0c\x66iscalNumber\x18\x03 \x01(\t\".\n\nClientList\x12 \n\x07\x63lients\x18\x01 \x03(\x0b\x32\x0f.texpact.Client2\x7f\n\rClientService\x12\x32\n\x0bListClients\x12\x0e.texpact.Empty\x1a\x13.texpact.ClientList\x12:\n\rGetClientById\x12\x18.texpact.ClientIdRequest\x1a\x0f.texpact.Clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clients_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_CLIENTIDREQUEST']._serialized_start=35
  _globals['_CLIENTIDREQUEST']._serialized_end=71
  _globals['_CLIENT']._serialized_start=73
  _globals['_CLIENT']._serialized_end=129
  _globals['_CLIENTLIST']._serialized_start=131
  _globals['_CLIENTLIST']._serialized_end=177
  _globals['_CLIENTSERVICE']._serialized_start=179
  _globals['_CLIENTSERVICE']._serialized_end=306
# @@protoc_insertion_point(module_scope)
