# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: container_localization.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'container_localization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ontainer_localization.proto\x12\x07texpact\x1a\x1bgoogle/protobuf/empty.proto\"\x89\x01\n\x15\x43ontainerLocalization\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63ontainerId\x18\x02 \x01(\x05\x12\x11\n\tsectionId\x18\x03 \x01(\x05\x12\x10\n\x08\x64\x61tetime\x18\x04 \x01(\t\x12\x15\n\rcontainerName\x18\x05 \x01(\t\x12\x13\n\x0bsectionName\x18\x06 \x01(\t\"J\n\x19\x43ontainerLocalizationList\x12-\n\x05items\x18\x01 \x03(\x0b\x32\x1e.texpact.ContainerLocalization\":\n%ContainerLocalizationBySectionRequest\x12\x11\n\tsectionId\x18\x01 \x01(\x05\"#\n\x15LocalizationIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\">\n\'ContainerLocalizationByContainerRequest\x12\x13\n\x0b\x63ontainerId\x18\x01 \x01(\x05\"9\n\x12SectionTimeRequest\x12\x11\n\tsectionId\x18\x01 \x01(\x05\x12\x10\n\x08\x64\x61tetime\x18\x02 \x01(\t2\xe8\x04\n\x1c\x43ontainerLocalizationService\x12X\n\x1aListContainerLocalizations\x12\x16.google.protobuf.Empty\x1a\".texpact.ContainerLocalizationList\x12\x63\n\rListBySection\x12..texpact.ContainerLocalizationBySectionRequest\x1a\".texpact.ContainerLocalizationList\x12I\n\x07GetById\x12\x1e.texpact.LocalizationIdRequest\x1a\x1e.texpact.ContainerLocalization\x12u\n\x1fListWithContainerNamesBySection\x12..texpact.ContainerLocalizationBySectionRequest\x1a\".texpact.ContainerLocalizationList\x12o\n\x17ListSectionsByContainer\x12\x30.texpact.ContainerLocalizationByContainerRequest\x1a\".texpact.ContainerLocalizationList\x12V\n\x13ListBySectionAtTime\x12\x1b.texpact.SectionTimeRequest\x1a\".texpact.ContainerLocalizationListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'container_localization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTAINERLOCALIZATION']._serialized_start=71
  _globals['_CONTAINERLOCALIZATION']._serialized_end=208
  _globals['_CONTAINERLOCALIZATIONLIST']._serialized_start=210
  _globals['_CONTAINERLOCALIZATIONLIST']._serialized_end=284
  _globals['_CONTAINERLOCALIZATIONBYSECTIONREQUEST']._serialized_start=286
  _globals['_CONTAINERLOCALIZATIONBYSECTIONREQUEST']._serialized_end=344
  _globals['_LOCALIZATIONIDREQUEST']._serialized_start=346
  _globals['_LOCALIZATIONIDREQUEST']._serialized_end=381
  _globals['_CONTAINERLOCALIZATIONBYCONTAINERREQUEST']._serialized_start=383
  _globals['_CONTAINERLOCALIZATIONBYCONTAINERREQUEST']._serialized_end=445
  _globals['_SECTIONTIMEREQUEST']._serialized_start=447
  _globals['_SECTIONTIMEREQUEST']._serialized_end=504
  _globals['_CONTAINERLOCALIZATIONSERVICE']._serialized_start=507
  _globals['_CONTAINERLOCALIZATIONSERVICE']._serialized_end=1123
# @@protoc_insertion_point(module_scope)
