# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import container_localization_pb2 as container__localization__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in container_localization_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContainerLocalizationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListContainerLocalizations = channel.unary_unary(
                '/texpact.ContainerLocalizationService/ListContainerLocalizations',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=container__localization__pb2.ContainerLocalizationList.FromString,
                _registered_method=True)
        self.ListBySection = channel.unary_unary(
                '/texpact.ContainerLocalizationService/ListBySection',
                request_serializer=container__localization__pb2.ContainerLocalizationBySectionRequest.SerializeToString,
                response_deserializer=container__localization__pb2.ContainerLocalizationList.FromString,
                _registered_method=True)
        self.GetById = channel.unary_unary(
                '/texpact.ContainerLocalizationService/GetById',
                request_serializer=container__localization__pb2.LocalizationIdRequest.SerializeToString,
                response_deserializer=container__localization__pb2.ContainerLocalization.FromString,
                _registered_method=True)
        self.ListWithContainerNamesBySection = channel.unary_unary(
                '/texpact.ContainerLocalizationService/ListWithContainerNamesBySection',
                request_serializer=container__localization__pb2.ContainerLocalizationBySectionRequest.SerializeToString,
                response_deserializer=container__localization__pb2.ContainerLocalizationList.FromString,
                _registered_method=True)
        self.ListSectionsByContainer = channel.unary_unary(
                '/texpact.ContainerLocalizationService/ListSectionsByContainer',
                request_serializer=container__localization__pb2.ContainerLocalizationByContainerRequest.SerializeToString,
                response_deserializer=container__localization__pb2.ContainerLocalizationList.FromString,
                _registered_method=True)
        self.ListBySectionAtTime = channel.unary_unary(
                '/texpact.ContainerLocalizationService/ListBySectionAtTime',
                request_serializer=container__localization__pb2.SectionTimeRequest.SerializeToString,
                response_deserializer=container__localization__pb2.ContainerLocalizationList.FromString,
                _registered_method=True)


class ContainerLocalizationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListContainerLocalizations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBySection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWithContainerNamesBySection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSectionsByContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBySectionAtTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContainerLocalizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListContainerLocalizations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContainerLocalizations,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=container__localization__pb2.ContainerLocalizationList.SerializeToString,
            ),
            'ListBySection': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBySection,
                    request_deserializer=container__localization__pb2.ContainerLocalizationBySectionRequest.FromString,
                    response_serializer=container__localization__pb2.ContainerLocalizationList.SerializeToString,
            ),
            'GetById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetById,
                    request_deserializer=container__localization__pb2.LocalizationIdRequest.FromString,
                    response_serializer=container__localization__pb2.ContainerLocalization.SerializeToString,
            ),
            'ListWithContainerNamesBySection': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWithContainerNamesBySection,
                    request_deserializer=container__localization__pb2.ContainerLocalizationBySectionRequest.FromString,
                    response_serializer=container__localization__pb2.ContainerLocalizationList.SerializeToString,
            ),
            'ListSectionsByContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSectionsByContainer,
                    request_deserializer=container__localization__pb2.ContainerLocalizationByContainerRequest.FromString,
                    response_serializer=container__localization__pb2.ContainerLocalizationList.SerializeToString,
            ),
            'ListBySectionAtTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBySectionAtTime,
                    request_deserializer=container__localization__pb2.SectionTimeRequest.FromString,
                    response_serializer=container__localization__pb2.ContainerLocalizationList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'texpact.ContainerLocalizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('texpact.ContainerLocalizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContainerLocalizationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListContainerLocalizations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ContainerLocalizationService/ListContainerLocalizations',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            container__localization__pb2.ContainerLocalizationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBySection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ContainerLocalizationService/ListBySection',
            container__localization__pb2.ContainerLocalizationBySectionRequest.SerializeToString,
            container__localization__pb2.ContainerLocalizationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ContainerLocalizationService/GetById',
            container__localization__pb2.LocalizationIdRequest.SerializeToString,
            container__localization__pb2.ContainerLocalization.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWithContainerNamesBySection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ContainerLocalizationService/ListWithContainerNamesBySection',
            container__localization__pb2.ContainerLocalizationBySectionRequest.SerializeToString,
            container__localization__pb2.ContainerLocalizationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSectionsByContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ContainerLocalizationService/ListSectionsByContainer',
            container__localization__pb2.ContainerLocalizationByContainerRequest.SerializeToString,
            container__localization__pb2.ContainerLocalizationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBySectionAtTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ContainerLocalizationService/ListBySectionAtTime',
            container__localization__pb2.SectionTimeRequest.SerializeToString,
            container__localization__pb2.ContainerLocalizationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
