# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: containers.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'containers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontainers.proto\x12\x07texpact\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n\tNameField\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x96\x01\n\tContainer\x12\x13\n\x0b\x63ontainerId\x18\x01 \x01(\x05\x12\x1e\n\x02id\x18\x02 \x01(\x0b\x32\x12.texpact.NameField\x12)\n\rcontainerName\x18\x03 \x01(\x0b\x32\x12.texpact.NameField\x12\x17\n\x0f\x63ontainerVolume\x18\x04 \x01(\x05\x12\x10\n\x08\x61\x63tivate\x18\x05 \x01(\x08\"7\n\rContainerList\x12&\n\ncontainers\x18\x01 \x03(\x0b\x32\x12.texpact.Container\")\n\x12\x43ontainerIdRequest\x12\x13\n\x0b\x63ontainerId\x18\x01 \x01(\x05\x32\x99\x01\n\x10\x43ontainerService\x12@\n\x0eListContainers\x12\x16.google.protobuf.Empty\x1a\x16.texpact.ContainerList\x12\x43\n\x10GetContainerById\x12\x1b.texpact.ContainerIdRequest\x1a\x12.texpact.Containerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'containers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAMEFIELD']._serialized_start=58
  _globals['_NAMEFIELD']._serialized_end=83
  _globals['_CONTAINER']._serialized_start=86
  _globals['_CONTAINER']._serialized_end=236
  _globals['_CONTAINERLIST']._serialized_start=238
  _globals['_CONTAINERLIST']._serialized_end=293
  _globals['_CONTAINERIDREQUEST']._serialized_start=295
  _globals['_CONTAINERIDREQUEST']._serialized_end=336
  _globals['_CONTAINERSERVICE']._serialized_start=339
  _globals['_CONTAINERSERVICE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
