# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import manufacturing_pb2 as manufacturing__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in manufacturing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManufacturingOrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/texpact.ManufacturingOrderService/List',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=manufacturing__pb2.ManufacturingOrderList.FromString,
                _registered_method=True)
        self.GetById = channel.unary_unary(
                '/texpact.ManufacturingOrderService/GetById',
                request_serializer=manufacturing__pb2.OrderIdRequest.SerializeToString,
                response_deserializer=manufacturing__pb2.ManufacturingOrder.FromString,
                _registered_method=True)
        self.ListRawMaterialsByOrder = channel.unary_unary(
                '/texpact.ManufacturingOrderService/ListRawMaterialsByOrder',
                request_serializer=manufacturing__pb2.OrderIdRequest.SerializeToString,
                response_deserializer=manufacturing__pb2.ItemOfRawMaterialList.FromString,
                _registered_method=True)
        self.ListPhasesByOrder = channel.unary_unary(
                '/texpact.ManufacturingOrderService/ListPhasesByOrder',
                request_serializer=manufacturing__pb2.OrderIdRequest.SerializeToString,
                response_deserializer=manufacturing__pb2.ManufacturingOrderPhaseList.FromString,
                _registered_method=True)
        self.ListHistoryByOrder = channel.unary_unary(
                '/texpact.ManufacturingOrderService/ListHistoryByOrder',
                request_serializer=manufacturing__pb2.OrderIdRequest.SerializeToString,
                response_deserializer=manufacturing__pb2.ManufacturingOrderHistoryList.FromString,
                _registered_method=True)


class ManufacturingOrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRawMaterialsByOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPhasesByOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHistoryByOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManufacturingOrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=manufacturing__pb2.ManufacturingOrderList.SerializeToString,
            ),
            'GetById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetById,
                    request_deserializer=manufacturing__pb2.OrderIdRequest.FromString,
                    response_serializer=manufacturing__pb2.ManufacturingOrder.SerializeToString,
            ),
            'ListRawMaterialsByOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRawMaterialsByOrder,
                    request_deserializer=manufacturing__pb2.OrderIdRequest.FromString,
                    response_serializer=manufacturing__pb2.ItemOfRawMaterialList.SerializeToString,
            ),
            'ListPhasesByOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPhasesByOrder,
                    request_deserializer=manufacturing__pb2.OrderIdRequest.FromString,
                    response_serializer=manufacturing__pb2.ManufacturingOrderPhaseList.SerializeToString,
            ),
            'ListHistoryByOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHistoryByOrder,
                    request_deserializer=manufacturing__pb2.OrderIdRequest.FromString,
                    response_serializer=manufacturing__pb2.ManufacturingOrderHistoryList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'texpact.ManufacturingOrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('texpact.ManufacturingOrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManufacturingOrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ManufacturingOrderService/List',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            manufacturing__pb2.ManufacturingOrderList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ManufacturingOrderService/GetById',
            manufacturing__pb2.OrderIdRequest.SerializeToString,
            manufacturing__pb2.ManufacturingOrder.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRawMaterialsByOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ManufacturingOrderService/ListRawMaterialsByOrder',
            manufacturing__pb2.OrderIdRequest.SerializeToString,
            manufacturing__pb2.ItemOfRawMaterialList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPhasesByOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ManufacturingOrderService/ListPhasesByOrder',
            manufacturing__pb2.OrderIdRequest.SerializeToString,
            manufacturing__pb2.ManufacturingOrderPhaseList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHistoryByOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ManufacturingOrderService/ListHistoryByOrder',
            manufacturing__pb2.OrderIdRequest.SerializeToString,
            manufacturing__pb2.ManufacturingOrderHistoryList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ItemLocalizationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/texpact.ItemLocalizationService/List',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=manufacturing__pb2.ItemLocalizationList.FromString,
                _registered_method=True)
        self.GetById = channel.unary_unary(
                '/texpact.ItemLocalizationService/GetById',
                request_serializer=manufacturing__pb2.ItemLocalizationRequest.SerializeToString,
                response_deserializer=manufacturing__pb2.ItemLocalization.FromString,
                _registered_method=True)
        self.ListByOrderItems = channel.unary_unary(
                '/texpact.ItemLocalizationService/ListByOrderItems',
                request_serializer=manufacturing__pb2.OrderIdRequest.SerializeToString,
                response_deserializer=manufacturing__pb2.ItemLocalizationList.FromString,
                _registered_method=True)


class ItemLocalizationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListByOrderItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemLocalizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=manufacturing__pb2.ItemLocalizationList.SerializeToString,
            ),
            'GetById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetById,
                    request_deserializer=manufacturing__pb2.ItemLocalizationRequest.FromString,
                    response_serializer=manufacturing__pb2.ItemLocalization.SerializeToString,
            ),
            'ListByOrderItems': grpc.unary_unary_rpc_method_handler(
                    servicer.ListByOrderItems,
                    request_deserializer=manufacturing__pb2.OrderIdRequest.FromString,
                    response_serializer=manufacturing__pb2.ItemLocalizationList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'texpact.ItemLocalizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('texpact.ItemLocalizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ItemLocalizationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ItemLocalizationService/List',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            manufacturing__pb2.ItemLocalizationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ItemLocalizationService/GetById',
            manufacturing__pb2.ItemLocalizationRequest.SerializeToString,
            manufacturing__pb2.ItemLocalization.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListByOrderItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.ItemLocalizationService/ListByOrderItems',
            manufacturing__pb2.OrderIdRequest.SerializeToString,
            manufacturing__pb2.ItemLocalizationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
