# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import plantfloorsection_pb2 as plantfloorsection__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in plantfloorsection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlantFloorSectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPlantFloorSections = channel.unary_unary(
                '/texpact.PlantFloorSectionService/ListPlantFloorSections',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=plantfloorsection__pb2.PlantFloorSectionList.FromString,
                _registered_method=True)
        self.GetPlantFloorSectionById = channel.unary_unary(
                '/texpact.PlantFloorSectionService/GetPlantFloorSectionById',
                request_serializer=plantfloorsection__pb2.PlantFloorSectionIdRequest.SerializeToString,
                response_deserializer=plantfloorsection__pb2.PlantFloorSection.FromString,
                _registered_method=True)


class PlantFloorSectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListPlantFloorSections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlantFloorSectionById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlantFloorSectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPlantFloorSections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlantFloorSections,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=plantfloorsection__pb2.PlantFloorSectionList.SerializeToString,
            ),
            'GetPlantFloorSectionById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlantFloorSectionById,
                    request_deserializer=plantfloorsection__pb2.PlantFloorSectionIdRequest.FromString,
                    response_serializer=plantfloorsection__pb2.PlantFloorSection.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'texpact.PlantFloorSectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('texpact.PlantFloorSectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlantFloorSectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListPlantFloorSections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.PlantFloorSectionService/ListPlantFloorSections',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            plantfloorsection__pb2.PlantFloorSectionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlantFloorSectionById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.PlantFloorSectionService/GetPlantFloorSectionById',
            plantfloorsection__pb2.PlantFloorSectionIdRequest.SerializeToString,
            plantfloorsection__pb2.PlantFloorSection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
