# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plantfloorsection.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'plantfloorsection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17plantfloorsection.proto\x12\x07texpact\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x16PlantFloorSectionField\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x82\x01\n\x11PlantFloorSection\x12\x11\n\tsectionId\x18\x01 \x01(\x05\x12+\n\x02id\x18\x02 \x01(\x0b\x32\x1f.texpact.PlantFloorSectionField\x12-\n\x04name\x18\x03 \x01(\x0b\x32\x1f.texpact.PlantFloorSectionField\"E\n\x15PlantFloorSectionList\x12,\n\x08sections\x18\x01 \x03(\x0b\x32\x1a.texpact.PlantFloorSection\"/\n\x1aPlantFloorSectionIdRequest\x12\x11\n\tsectionId\x18\x01 \x01(\x05\x32\xc9\x01\n\x18PlantFloorSectionService\x12P\n\x16ListPlantFloorSections\x12\x16.google.protobuf.Empty\x1a\x1e.texpact.PlantFloorSectionList\x12[\n\x18GetPlantFloorSectionById\x12#.texpact.PlantFloorSectionIdRequest\x1a\x1a.texpact.PlantFloorSectionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plantfloorsection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLANTFLOORSECTIONFIELD']._serialized_start=65
  _globals['_PLANTFLOORSECTIONFIELD']._serialized_end=103
  _globals['_PLANTFLOORSECTION']._serialized_start=106
  _globals['_PLANTFLOORSECTION']._serialized_end=236
  _globals['_PLANTFLOORSECTIONLIST']._serialized_start=238
  _globals['_PLANTFLOORSECTIONLIST']._serialized_end=307
  _globals['_PLANTFLOORSECTIONIDREQUEST']._serialized_start=309
  _globals['_PLANTFLOORSECTIONIDREQUEST']._serialized_end=356
  _globals['_PLANTFLOORSECTIONSERVICE']._serialized_start=359
  _globals['_PLANTFLOORSECTIONSERVICE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
