# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: products.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'products.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x07texpact\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\rProductsField\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x8c\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12$\n\x04name\x18\x03 \x01(\x0b\x32\x16.texpact.ProductsField\x12$\n\x04info\x18\x04 \x01(\x0b\x32\x16.texpact.ProductsField\x12)\n\tproductId\x18\x05 \x01(\x0b\x32\x16.texpact.ProductsField\"1\n\x0bProductList\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.texpact.Product\"%\n\x10ProductIdRequest\x12\x11\n\tProductId\x18\x01 \x01(\x05\x32\x8d\x01\n\x0eProductService\x12<\n\x0cListProducts\x12\x16.google.protobuf.Empty\x1a\x14.texpact.ProductList\x12=\n\x0eGetProductById\x12\x19.texpact.ProductIdRequest\x1a\x10.texpact.Productb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTSFIELD']._serialized_start=56
  _globals['_PRODUCTSFIELD']._serialized_end=85
  _globals['_PRODUCT']._serialized_start=88
  _globals['_PRODUCT']._serialized_end=228
  _globals['_PRODUCTLIST']._serialized_start=230
  _globals['_PRODUCTLIST']._serialized_end=279
  _globals['_PRODUCTIDREQUEST']._serialized_start=281
  _globals['_PRODUCTIDREQUEST']._serialized_end=318
  _globals['_PRODUCTSERVICE']._serialized_start=321
  _globals['_PRODUCTSERVICE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
