# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rawmaterials.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'rawmaterials.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12rawmaterials.proto\x12\x07texpact\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0cRawNameField\x12\x0c\n\x04name\x18\x01 \x01(\t\"f\n\x0bRawMaterial\x12\r\n\x05rawId\x18\x01 \x01(\x05\x12#\n\x04name\x18\x03 \x01(\x0b\x32\x15.texpact.RawNameField\x12#\n\x04info\x18\x04 \x01(\x0b\x32\x15.texpact.RawNameField\"=\n\x0fRawMaterialList\x12*\n\x0crawmaterials\x18\x01 \x03(\x0b\x32\x14.texpact.RawMaterial\"-\n\x14RawMaterialIdRequest\x12\x15\n\rRawMaterialId\x18\x01 \x01(\x05\x32\xa5\x01\n\x12RawMaterialService\x12\x44\n\x10ListRawMaterials\x12\x16.google.protobuf.Empty\x1a\x18.texpact.RawMaterialList\x12I\n\x12GetRawMaterialById\x12\x1d.texpact.RawMaterialIdRequest\x1a\x14.texpact.RawMaterialb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rawmaterials_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAWNAMEFIELD']._serialized_start=60
  _globals['_RAWNAMEFIELD']._serialized_end=88
  _globals['_RAWMATERIAL']._serialized_start=90
  _globals['_RAWMATERIAL']._serialized_end=192
  _globals['_RAWMATERIALLIST']._serialized_start=194
  _globals['_RAWMATERIALLIST']._serialized_end=255
  _globals['_RAWMATERIALIDREQUEST']._serialized_start=257
  _globals['_RAWMATERIALIDREQUEST']._serialized_end=302
  _globals['_RAWMATERIALSERVICE']._serialized_start=305
  _globals['_RAWMATERIALSERVICE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
