# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import rawmaterials_pb2 as rawmaterials__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rawmaterials_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RawMaterialServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListRawMaterials = channel.unary_unary(
                '/texpact.RawMaterialService/ListRawMaterials',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=rawmaterials__pb2.RawMaterialList.FromString,
                _registered_method=True)
        self.GetRawMaterialById = channel.unary_unary(
                '/texpact.RawMaterialService/GetRawMaterialById',
                request_serializer=rawmaterials__pb2.RawMaterialIdRequest.SerializeToString,
                response_deserializer=rawmaterials__pb2.RawMaterial.FromString,
                _registered_method=True)


class RawMaterialServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListRawMaterials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRawMaterialById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RawMaterialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListRawMaterials': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRawMaterials,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=rawmaterials__pb2.RawMaterialList.SerializeToString,
            ),
            'GetRawMaterialById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRawMaterialById,
                    request_deserializer=rawmaterials__pb2.RawMaterialIdRequest.FromString,
                    response_serializer=rawmaterials__pb2.RawMaterial.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'texpact.RawMaterialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('texpact.RawMaterialService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RawMaterialService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListRawMaterials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.RawMaterialService/ListRawMaterials',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            rawmaterials__pb2.RawMaterialList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRawMaterialById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/texpact.RawMaterialService/GetRawMaterialById',
            rawmaterials__pb2.RawMaterialIdRequest.SerializeToString,
            rawmaterials__pb2.RawMaterial.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
