# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2024-12-04T18:36:19+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Type(Enum):
    ManufacturingMachine = 'ManufacturingMachine'


class DataModelPlataform(BaseModel):
    id: str = Field(..., description='Property. Unique identifier for the container')
    type: Type = Field(..., description='Property. It has to be ManufacturingMachine')
    name: str = Field(..., description='Property. Name of the container')
    volume: Optional[float] = Field(
        None,
        description='Property. Volume of the container (in cubic meters or appropriate unit)',
    )
    description: Optional[str] = Field(
        None, description='Property. Detailed description of the container.'
    )
